"""initial schema

Revision ID: 0fb99da0fbc7
Revises: 
Create Date: 2023-11-07 12:18:21.530404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb99da0fbc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('mmtx_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_sources_id'), 'camera_sources', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('s3_bucket', sa.String(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('inferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Double(), nullable=True),
    sa.Column('source_kind', sa.Enum('Video', 'Camera', 'Config', name='sourcekind'), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inferences_id'), 'inferences', ['id'], unique=False)
    op.create_table('inference_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Double(), nullable=True),
    sa.Column('y', sa.Double(), nullable=True),
    sa.Column('w', sa.Double(), nullable=True),
    sa.Column('h', sa.Double(), nullable=True),
    sa.Column('inference_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['inference_id'], ['inferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_hits_id'), 'inference_hits', ['id'], unique=False)
    op.create_table('video_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('t_start', sa.Double(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_sources_id'), 'video_sources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_sources_id'), table_name='video_sources')
    op.drop_table('video_sources')
    op.drop_index(op.f('ix_inference_hits_id'), table_name='inference_hits')
    op.drop_table('inference_hits')
    op.drop_index(op.f('ix_inferences_id'), table_name='inferences')
    op.drop_table('inferences')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_camera_sources_id'), table_name='camera_sources')
    op.drop_table('camera_sources')
    # ### end Alembic commands ###
