"""add active for sources

Revision ID: 148e581b9765
Revises: dbb1f3f3cdc5
Create Date: 2023-11-11 12:29:38.615698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148e581b9765'
down_revision: Union[str, None] = 'dbb1f3f3cdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera_sources', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('video_sources', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_sources', 'is_active')
    op.drop_column('camera_sources', 'is_active')
    # ### end Alembic commands ###
