"""cascade delete inference hits

Revision ID: 43bdf4b9430c
Revises: 0fb99da0fbc7
Create Date: 2023-11-07 16:21:13.214408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43bdf4b9430c'
down_revision: Union[str, None] = '0fb99da0fbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
